// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for default seo documents */
interface DfaultSeoDocumentData {
    /**
     * meta title field in *default seo*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: dfault_seo.meta_title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    meta_title: prismicT.RichTextField;
    /**
     * meta description field in *default seo*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: dfault_seo.meta_description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    meta_description: prismicT.RichTextField;
    /**
     * meta image field in *default seo*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: dfault_seo.meta_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    meta_image: prismicT.ImageField<never>;
}
/**
 * default seo document from Prismic
 *
 * - **API ID**: `dfault_seo`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DfaultSeoDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<DfaultSeoDocumentData>, "dfault_seo", Lang>;
/** Content for Menu documents */
interface MenuDocumentData {
    /**
     * Menu items field in *Menu*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.menu_items[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    menu_items: prismicT.GroupField<Simplify<MenuDocumentDataMenuItemsItem>>;
    /**
     * Logo field in *Menu*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.logo
     * - **Tab**: Logo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
}
/**
 * Item in Menu → Menu items
 *
 */
export interface MenuDocumentDataMenuItemsItem {
    /**
     * Label field in *Menu → Menu items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.menu_items[].label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    label: prismicT.KeyTextField;
    /**
     * Link field in *Menu → Menu items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: menu.menu_items[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
}
/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;
/** Content for Page documents */
interface PageDocumentData {
    /**
     * Title field in *Page*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PageDocumentDataSlicesSlice>;
    /**
     * meta title field in *Page*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.meta_title
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    meta_title: prismicT.RichTextField;
    /**
     * meta description field in *Page*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: page.meta_description
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    meta_description: prismicT.RichTextField;
    /**
     * meta image field in *Page*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: page.meta_image
     * - **Tab**: SEO
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    meta_image: prismicT.ImageField<never>;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = VideoSectionSlice | AboutSectionSlice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
export type AllDocumentTypes = DfaultSeoDocument | MenuDocument | PageDocument;
/**
 * Primary content in AboutSection → Primary
 *
 */
interface AboutSectionSliceDefaultPrimary {
    /**
     * Number field in *AboutSection → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about_section.primary.number
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    number: prismicT.RichTextField;
    /**
     * Title field in *AboutSection → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: about_section.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Slogan field in *AboutSection → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about_section.primary.slogan
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    slogan: prismicT.RichTextField;
    /**
     * Description field in *AboutSection → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: about_section.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for AboutSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: `AboutSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AboutSectionSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<AboutSectionSliceDefaultPrimary>, never>;
/**
 * Primary content in AboutSection → Primary
 *
 */
interface AboutSectionSliceTitleFirstPrimary {
    /**
     * Title field in *AboutSection → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: about_section.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Number field in *AboutSection → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about_section.primary.number
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    number: prismicT.RichTextField;
    /**
     * Slogan field in *AboutSection → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about_section.primary.slogan
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    slogan: prismicT.RichTextField;
    /**
     * Description field in *AboutSection → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: about_section.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * title first variation for AboutSection Slice
 *
 * - **API ID**: `titleFirst`
 * - **Description**: `AboutSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AboutSectionSliceTitleFirst = prismicT.SharedSliceVariation<"titleFirst", Simplify<AboutSectionSliceTitleFirstPrimary>, never>;
/**
 * Slice variation for *AboutSection*
 *
 */
type AboutSectionSliceVariation = AboutSectionSliceDefault | AboutSectionSliceTitleFirst;
/**
 * AboutSection Shared Slice
 *
 * - **API ID**: `about_section`
 * - **Description**: `AboutSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type AboutSectionSlice = prismicT.SharedSlice<"about_section", AboutSectionSliceVariation>;
/**
 * Primary content in VideoSection → Primary
 *
 */
interface VideoSectionSliceDefaultPrimary {
    /**
     * Title field in *VideoSection → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: video_section.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Slogan field in *VideoSection → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: video_section.primary.slogan
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    slogan: prismicT.RichTextField;
    /**
     * Description field in *VideoSection → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: video_section.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for VideoSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: `VideoSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type VideoSectionSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<VideoSectionSliceDefaultPrimary>, never>;
/**
 * Slice variation for *VideoSection*
 *
 */
type VideoSectionSliceVariation = VideoSectionSliceDefault;
/**
 * VideoSection Shared Slice
 *
 * - **API ID**: `video_section`
 * - **Description**: `VideoSection`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type VideoSectionSlice = prismicT.SharedSlice<"video_section", VideoSectionSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { DfaultSeoDocumentData, DfaultSeoDocument, MenuDocumentData, MenuDocumentDataMenuItemsItem, MenuDocument, PageDocumentData, PageDocumentDataSlicesSlice, PageDocument, AllDocumentTypes, AboutSectionSliceDefaultPrimary, AboutSectionSliceDefault, AboutSectionSliceTitleFirstPrimary, AboutSectionSliceTitleFirst, AboutSectionSliceVariation, AboutSectionSlice, VideoSectionSliceDefaultPrimary, VideoSectionSliceDefault, VideoSectionSliceVariation, VideoSectionSlice };
    }
}
