// Code generated by Slice Machine. DO NOT EDIT.

import AboutSection from './AboutSection';
import VideoSection from './VideoSection';

export {
	AboutSection,
	VideoSection,
};

export const components = {
	about_section: AboutSection,
	video_section: VideoSection,
};
